# Generated by Django 2.2.23 on 2021-10-17 09:44

import champion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('champion_type', models.CharField(choices=[('1', 'Institutional'), ('2', 'Faculty'), ('3', 'Organisational')], max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image_file', models.ImageField(upload_to='')),
                ('contact_one', models.CharField(max_length=10, validators=[champion.models.phone_val])),
                ('contact_two', models.CharField(blank=True, max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('current_year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], max_length=10)),
                ('local_address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('aadhar_file', models.ImageField(upload_to='')),
                ('pan_id', models.CharField(max_length=10)),
                ('pan_file', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField()),
                ('achievements', models.TextField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='address.Country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution', to='institution.Institution')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='address.State')),
            ],
        ),
    ]
