# Generated by Django 2.2.23 on 2021-10-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionFocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('focal_type', models.CharField(choices=[('1', 'Primary'), ('2', 'Escalation')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('local_address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=6)),
                ('sponsor_type', models.CharField(choices=[('1', 'Title'), ('2', 'Campaign'), ('3', 'Travel'), ('4', 'Techonology'), ('5', 'Media'), ('6', 'Regional'), ('7', 'Hospitality')], max_length=20)),
                ('creation_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insti_country', to='address.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insit_state', to='address.State')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_logo', models.ImageField(upload_to='')),
                ('ed_cell', models.BooleanField()),
                ('total_no_students', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=6)),
                ('institution_reg_no', models.CharField(max_length=100, unique=True)),
                ('sponsored_amounts', models.IntegerField(editable=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_insti', to='address.Country')),
                ('incubation_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incub', to='incubation.Incubation')),
                ('insti_focals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.InstitutionFocal')),
                ('region', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, related_name='region_insti', to='address.Region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_insti', to='address.State')),
            ],
        ),
    ]
