# Generated by Django 2.2.23 on 2021-10-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='sponsored_amounts',
        ),
    ]
