# Generated by Django 2.2.23 on 2021-10-20 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThinkTankProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('think_tank_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('profile_status', models.BooleanField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], default=None, max_length=6)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('current_year', models.IntegerField()),
                ('creation_dateTime', models.DateTimeField()),
                ('update_dateTime', models.DateTimeField(auto_now=True)),
                ('is_ebc', models.BooleanField()),
                ('total_family_members', models.IntegerField()),
                ('born_brought_up_at', models.CharField(max_length=200)),
                ('earners_in_family', models.IntegerField()),
                ('no_of_people_doing_jobs', models.IntegerField()),
                ('no_of_people_doing_farming', models.IntegerField()),
                ('no_of_people_doing_business', models.IntegerField()),
                ('branch', models.CharField(max_length=200)),
                ('think_tank_image', models.ImageField(blank=True, default='ThinkTankProfile/user-default.png', null=True, upload_to='ThinkTankProfile/')),
            ],
        ),
    ]
