# Generated by Django 2.2.23 on 2021-10-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationFocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focal_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('focal_type', models.CharField(choices=[('Primary', 'Primary'), ('Escalation', 'Escalation')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incubation_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('incubation_logo', models.ImageField(upload_to='')),
                ('supported_by', models.CharField(choices=[('1', 'MSME'), ('2', 'AIC'), ('3', 'MSINS'), ('4', 'Private Organisation'), ('5', 'Government Organisation'), ('6', 'Other')], max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc_country', to='address.Country')),
                ('incubation_focal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='focal', to='incubation.IncubationFocal')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inc_region', to='address.Region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc_state', to='address.State')),
            ],
        ),
    ]
