# Generated by Django 2.2.23 on 2021-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('image_event_name', models.CharField(max_length=50)),
                ('image_file', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_desc', models.TextField()),
                ('image_file', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField()),
                ('partner_type', models.CharField(choices=[('1', 'Outreach'), ('2', 'Youth Empowerment'), ('3', 'Government')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsor_desc', models.TextField()),
                ('image_file', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField()),
                ('sponsor_type', models.CharField(choices=[('1', 'Title'), ('2', 'Campaign'), ('3', 'Travel'), ('4', 'Techonology'), ('5', 'Media'), ('6', 'Regional'), ('7', 'Hospitality')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YouthIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('image_file', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
