# Generated by Django 2.2.23 on 2021-10-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalyst_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('user_image', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('gender', models.CharField(choices=[('1', 'M'), ('2', 'F'), ('3', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_one', models.CharField(max_length=10)),
                ('contact_two', models.CharField(blank=True, max_length=10)),
                ('local_address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('aadhar_file', models.ImageField(upload_to='')),
                ('pan_id', models.CharField(max_length=10)),
                ('pan_file', models.ImageField(upload_to='')),
                ('catalyst_type', models.CharField(choices=[('1', 'Student'), ('2', 'Faculty')], max_length=10)),
                ('current_year', models.CharField(blank=True, choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'NA')], max_length=5)),
                ('years_of_experience', models.IntegerField()),
                ('rating', models.CharField(blank=True, choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=10)),
                ('number_of_quizzes', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_cont', to='address.Country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_insti', to='institution.Institution')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_state', to='address.State')),
            ],
        ),
    ]
