# Generated by Django 2.2.23 on 2021-10-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champion', '0001_initial'),
        ('address', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Event', 'Event'), ('Ceremony', 'Ceremony'), ('Workshop', 'Workshop')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('imp_notes', models.TextField()),
                ('Expected_no_of_candidates', models.IntegerField()),
                ('stationary_requirements', models.TextField()),
                ('is_event_online', models.BooleanField()),
                ('stay', models.BooleanField()),
                ('travel', models.BooleanField()),
                ('projector', models.BooleanField()),
                ('AV_setup', models.BooleanField()),
                ('infrastructural_requirements', models.TextField()),
                ('event_images', models.ImageField(upload_to='')),
                ('banner', models.ImageField(upload_to='')),
                ('attendees_from_evolvingx', models.IntegerField()),
                ('Event_summary', models.TextField(blank=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_champ_id', to='champion.Champion')),
                ('institutiion_sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_sponsor', to='institution.InstitutionSponsor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_region', to='address.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Event', 'Event'), ('Ceremony', 'Ceremony'), ('Workshop', 'Workshop')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('imp_notes', models.TextField()),
                ('EXpected_no_of_candidates', models.IntegerField()),
                ('stationary_requirements', models.TextField()),
                ('is_event_online', models.BooleanField()),
                ('stay', models.BooleanField()),
                ('travel', models.BooleanField()),
                ('projector', models.BooleanField()),
                ('av_setup', models.BooleanField()),
                ('infrastructural_requirements', models.TextField()),
                ('event_images', models.ImageField(upload_to='')),
                ('banner', models.ImageField(upload_to='')),
                ('attendees_from_evolvingx', models.IntegerField()),
                ('Event_summary', models.TextField(blank=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_champ_id', to='champion.Champion')),
                ('institutiion_sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_sponsor', to='institution.InstitutionSponsor')),
                ('regions_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_region', to='address.Region')),
            ],
        ),
    ]
