# Generated by Django 2.2.23 on 2021-10-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('country_name', models.CharField(choices=[('India', 'India')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('region_name', models.CharField(choices=[('1', 'Vidarbha'), ('2', 'Marathwada'), ('3', 'Konkan'), ('4', 'Khandesh'), ('5', 'Paschim Maharashtra')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('state_name', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('jammu & Kashmir', 'jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('district_name', models.CharField(max_length=30)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.State')),
            ],
        ),
    ]
