# Generated by Django 2.2.23 on 2022-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(choices=[('Vidarbha', 'vidarbha'), ('Marathwada', 'marathwada'), ('Konkan', 'konkan'), ('Khandesh', 'khandesh'), ('Paschim Maharashtra', 'paschim maharashtra')], max_length=20),
        ),
    ]
